# Generated by Django 3.1 on 2022-05-08 11:47

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms_count', models.SmallIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('comfortable', models.CharField(blank=True, max_length=200, null=True)),
                ('max_guest', models.SmallIntegerField()),
                ('arena_timeline', models.CharField(choices=[('OneDay', 'OneDay'), ('LongTime', 'LongTime')], max_length=200)),
                ('total_area', models.SmallIntegerField()),
                ('date_publish', models.DateTimeField(auto_now=True)),
                ('avg_rating', models.FloatField(default=0, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('cost', models.PositiveBigIntegerField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_guest', models.PositiveIntegerField()),
                ('lease_duration', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('cost_of_rent', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='flat.flat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='flat_images')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.flat')),
            ],
        ),
    ]
