# Generated by Django 3.1 on 2022-02-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flat", "0002_auto_20220203_0844"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flat",
            old_name="date_publisher",
            new_name="date_publish",
        ),
    ]
