# Generated by Django 3.1 on 2022-05-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_auto_20220508_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='avg_rating',
            field=models.FloatField(default=0, null=True, verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='comfortable',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rent_timeline',
            field=models.CharField(choices=[('OneDay', 'OneDay'), ('LongTime', 'LongTime')], max_length=200, verbose_name='Тип аренды'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='total_area',
            field=models.SmallIntegerField(verbose_name='Квандратура квартиры'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offer', to='flat.flat'),
        ),
    ]
