# Generated by Django 3.1 on 2022-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_auto_20220508_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
