# Generated by Django 3.1 on 2022-02-08 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flat", "0003_auto_20220208_0622"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="photos",
        ),
    ]
