# Generated by Django 3.1 on 2022-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_renting_is_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='id_payment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
