# Generated by Django 3.1 on 2022-05-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0005_renting_id_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='id_payment',
            field=models.CharField(max_length=200),
        ),
    ]
