# Generated by Django 3.1 on 2022-05-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0006_auto_20220502_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='cost_of_rent',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
