# Generated by Django 3.1 on 2022-05-03 10:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0007_renting_cost_of_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_list', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('cost', models.PositiveBigIntegerField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.flat')),
            ],
        ),
    ]
