# Generated by Django 3.1 on 2022-05-03 10:16

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0008_specialoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='date_list',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='date',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=None),
        ),
    ]
