# Generated by Django 3.1 on 2022-05-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0006_auto_20220224_1024'),
        ('flat', '0010_auto_20220503_1016'),
    ]

    operations = [
    ]
