# Generated by Django 3.1 on 2022-05-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0011_merge_20220507_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='date_publisher',
            new_name='date_publish',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='photos',
        ),
    ]
