version: '3.7'
services:
  web:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh entrypoint.sh

    volumes:
      - static_volume:/home/static
      - .:/home/easy_flat/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    env_file:
      - ./.env

  nginx:
    build: ./docker_configs/nginx/
    volumes:
      - static_volume:/home/static
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: