version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn easy_flat.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/path/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=database
    env_file:
      - ./.env

  nginx:
    build: ./docker_configs/nginx/
    volumes:
      - static_volume:/path/
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:

