# Generated by Django 3.1 on 2022-02-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avg_rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
