# Generated by Django 3.1 on 2022-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20220224_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avg_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
