# Generated by Django 3.1 on 2022-05-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220224_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
